# Generated by Django 3.1.3 on 2021-01-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(default='_', max_length=100)),
                ('img', models.ImageField(default='_', upload_to='img')),
                ('occupation', models.CharField(default='_', max_length=100)),
                ('phone', models.CharField(default='_', max_length=100)),
                ('birthday', models.CharField(default='_', max_length=100)),
            ],
            options={
                'db_table': 'signup_login_userprofile',
            },
        ),
    ]
